import { logStore } from '../../config/setting';

export const fs = require('fs');
export const moment = require('moment');
export const tomlify = require('tomlify-j0.4');
export const dateTimeFormatOperation: string = 'YYYY-MM-DD HH:mm:ss';
let operationCodeGlobal = 0;
let operationIncrementalProcess = 0;

export interface OperationInterface {
    operationCode: number; // It will be generated by System
    operation: string; // It Should String eg. Git, Repository
    running: boolean; // Indicating Process is running
    message: string;
    log: OperationLogInterface[];
}

export interface OperationLogInterface {
    name: string;
    description: string;
    status: 'error' | 'normal' | 'warning' | 'danger';
    finish: boolean;
}

export class OperationLog implements OperationLogInterface {
    startTime: string;
    stopTime: string = '';
    description: string;
    name: string;
    status: 'error' | 'normal' | 'warning' | 'danger';
    finish: boolean = false;

    constructor(name: string, description: string, status: 'error' | 'normal' | 'warning' | 'danger') {
        this.startTime = moment().format(dateTimeFormatOperation);
        this.description = description;
        this.name = name;
        this.status = status;
    }

    stop() {
        this.stopTime = moment().format(dateTimeFormatOperation);
        this.finish = true;
    }
}

export class Operation implements OperationInterface {
    log: OperationLogInterface[] = [];
    message: string = '';
    operation: string = '';
    operationCode: number = 0;
    running: boolean = true;
    startTime: string = '';
    stopTime: string = '';
    notFinishOperation: number = 0;
    finishOperation: number = 0;
    totalOperation: number = 0;

    constructor(operation: string, message: string) {
        operationCodeGlobal = operationCodeGlobal + 1;
        this.operation = operation;
        this.operationCode = operationCodeGlobal;
        this.message = message;
        this.startTime = moment().format(dateTimeFormatOperation);
        operationIncrementalProcess += 1;
    }

    stop() {
        this.stopTime = moment().format(dateTimeFormatOperation);
        for (let x of this.log) {
            if (x.finish) {
                this.notFinishOperation = this.notFinishOperation - 1;
                this.finishOperation = this.finishOperation + 1;
            }
        }
        this.running = false;
        const toml = tomlify.toToml(this, {space: 2});
        const nameLog = this.operation.split(' ').map((x: string) => {
            return x.toLowerCase();
        }).join('-');
        const fileName = operationIncrementalProcess.toString().concat('-').concat(this.operationCode.toString()).concat('-').concat(nameLog);
        const dateTime = moment().format('YYYYMMDDHHmmss');
        const location = logStore.concat('/').concat(dateTime).concat('-').concat(fileName).concat('.toml');
        operationCodeGlobal = operationCodeGlobal - 1;
        fs.writeFileSync(location, toml);
    }

    addOperationLog(name: string, description: string, status: 'error' | 'normal' | 'warning' | 'danger' = 'normal'): OperationLog {
        const operationLog: OperationLog = new OperationLog(name, description, status);
        this.log.push(operationLog);
        this.totalOperation = this.log.length;
        this.notFinishOperation = this.log.length;
        return operationLog;
    }

    setOperationLogFinish(operationLog: OperationLog) {
        operationLog.stop();
        const index: number = this.log.indexOf(operationLog);
        if (typeof index != 'undefined') {
            this.log[index] = operationLog;
        }
    }

    isNotFinish() {
        return !this.running;
    }
}
