dependency = [
  "npm"
]
name = "Angular"
description = "Script deployment for Angular"

[[command]]
command = "npm install"
description = "Download all package"
directory = []

[[command]]
command = "ng build"
description = "Compile Angular"
directory = []